---
title: "MUSA 8010"
author: "Jingyi Li"
date: "2024-02-24"
output: html_document
---

```{r setup, include=FALSE,warning = FALSE, message = FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(ggplot2)
library(grid)
library(gridExtra)
palettebase <- c("#7ACFD3","#67C8C8","#54C1C6","#41BAC0","#3AA8AE","#33969B","#2D8388","#016F74","#005357")
paletteaccent <- c("#46AFB4","#249DA2","#01939A","#017278","#005A5E","#FFCB62","#FFBD37","#FFAB00","#C68500","#9C6900","#FF6662","#FF3C37","#FF0700","#C60500","#9C0400")
```

## Load Data

  Considering car ownership is helpful to distinguish where the higher potential need for public transportation is located. Which can further help identifying which region might have higher possible ridership and which region exist the problem of underperforming.
  
```{r cars}
AllData<-read_csv("AllDat.csv") #%>% st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326)
dat2017 <- 
  get_acs(geography = "tract", 
          variables = c("B08301_001E","B08301_011E",
                        "B08201_001E","B08201_002E",
                        "B08201_003E","B08201_004E",
                        "B08201_005E","B08201_006E",
                        "B08201_007E"), 
          year=2017, state=37, county=119, 
          geometry=TRUE, output="wide") %>%
  st_transform(crs=4326) %>%
  rename(Total = B08201_001E,
         car0 = B08201_002E,
         car1 = B08201_003E,
         car2 = B08201_004E,
         car3 = B08201_005E,
         car4 = B08201_006E,
         car5more = B08201_007E,
         Commutetowork = B08301_001E,
         Workwithbus = B08301_011E) %>%
  mutate(pctworkwithbus = ifelse(Commutetowork > 0, Workwithbus / Commutetowork, 0),
         pctnocar = ifelse(Total > 0, car0 / Total, 0),
         pct1car = ifelse(Total > 0, car1 / Total, 0),
         pct2car = ifelse(Total > 0, car2 / Total, 0),
         pct3car = ifelse(Total > 0, car3 / Total, 0),
         pct4car = ifelse(Total > 0, car4 / Total, 0),
         pct5car = ifelse(Total > 0, car5more / Total, 0),
         year = "2017")

dat2018<- 
  get_acs(geography = "tract", 
          variables = c("B08301_001E","B08301_011E",
                        "B08201_001E","B08201_002E",
                        "B08201_003E","B08201_004E",
                        "B08201_005E","B08201_006E",
                        "B08201_007E"), 
          year=2018, state=37, county=119, 
          geometry=TRUE, output="wide") %>%
  st_transform(crs=4326) %>%
  rename(Total = B08201_001E,
         car0 = B08201_002E,
         car1 = B08201_003E,
         car2 = B08201_004E,
         car3 = B08201_005E,
         car4 = B08201_006E,
         car5more = B08201_007E,
         Commutetowork = B08301_001E,
         Workwithbus = B08301_011E) %>%
  mutate(pctworkwithbus = ifelse(Commutetowork > 0, Workwithbus / Commutetowork, 0),
         pctnocar = ifelse(Total > 0, car0 / Total, 0),
         pct1car = ifelse(Total > 0, car1 / Total, 0),
         pct2car = ifelse(Total > 0, car2 / Total, 0),
         pct3car = ifelse(Total > 0, car3 / Total, 0),
         pct4car = ifelse(Total > 0, car4 / Total, 0),
         pct5car = ifelse(Total > 0, car5more / Total, 0),
         year = "2018")
dat2019<- 
  get_acs(geography = "tract", 
          variables = c("B08301_001E","B08301_011E",
                        "B08201_001E","B08201_002E",
                        "B08201_003E","B08201_004E",
                        "B08201_005E","B08201_006E",
                        "B08201_007E"), 
          year=2019, state=37, county=119, 
          geometry=TRUE, output="wide") %>%
  st_transform(crs=4326) %>%
  rename(Total = B08201_001E,
         car0 = B08201_002E,
         car1 = B08201_003E,
         car2 = B08201_004E,
         car3 = B08201_005E,
         car4 = B08201_006E,
         car5more = B08201_007E,
         Commutetowork = B08301_001E,
         Workwithbus = B08301_011E) %>%
  mutate(pctworkwithbus = ifelse(Commutetowork > 0, Workwithbus / Commutetowork, 0),
         pctnocar = ifelse(Total > 0, car0 / Total, 0),
         pct1car = ifelse(Total > 0, car1 / Total, 0),
         pct2car = ifelse(Total > 0, car2 / Total, 0),
         pct3car = ifelse(Total > 0, car3 / Total, 0),
         pct4car = ifelse(Total > 0, car4 / Total, 0),
         pct5car = ifelse(Total > 0, car5more / Total, 0),
         year = "2019")

dat2020<- 
  get_acs(geography = "tract", 
          variables = c("B08301_001E","B08301_011E",
                        "B08201_001E","B08201_002E",
                        "B08201_003E","B08201_004E",
                        "B08201_005E","B08201_006E",
                        "B08201_007E"), 
          year=2020, state=37, county=119, 
          geometry=TRUE, output="wide") %>%
  st_transform(crs=4326) %>%
  rename(Total = B08201_001E,
         car0 = B08201_002E,
         car1 = B08201_003E,
         car2 = B08201_004E,
         car3 = B08201_005E,
         car4 = B08201_006E,
         car5more = B08201_007E,
         Commutetowork = B08301_001E,
         Workwithbus = B08301_011E) %>%
  mutate(pctworkwithbus = ifelse(Commutetowork > 0, Workwithbus / Commutetowork, 0),
         pctnocar = ifelse(Total > 0, car0 / Total, 0),
         pct1car = ifelse(Total > 0, car1 / Total, 0),
         pct2car = ifelse(Total > 0, car2 / Total, 0),
         pct3car = ifelse(Total > 0, car3 / Total, 0),
         pct4car = ifelse(Total > 0, car4 / Total, 0),
         pct5car = ifelse(Total > 0, car5more / Total, 0),
         year = "2020")

dat2021<- 
  get_acs(geography = "tract", 
          variables = c("B08301_001E","B08301_011E",
                        "B08201_001E","B08201_002E",
                        "B08201_003E","B08201_004E",
                        "B08201_005E","B08201_006E",
                        "B08201_007E"), 
          year=2021, state=37, county=119, 
          geometry=TRUE, output="wide") %>%
  st_transform(crs=4326) %>%
  rename(Total = B08201_001E,
         car0 = B08201_002E,
         car1 = B08201_003E,
         car2 = B08201_004E,
         car3 = B08201_005E,
         car4 = B08201_006E,
         car5more = B08201_007E,
         Commutetowork = B08301_001E,
         Workwithbus = B08301_011E) %>%
  mutate(pctworkwithbus = ifelse(Commutetowork > 0, Workwithbus / Commutetowork, 0),
         pctnocar = ifelse(Total > 0, car0 / Total, 0),
         pct1car = ifelse(Total > 0, car1 / Total, 0),
         pct2car = ifelse(Total > 0, car2 / Total, 0),
         pct3car = ifelse(Total > 0, car3 / Total, 0),
         pct4car = ifelse(Total > 0, car4 / Total, 0),
         pct5car = ifelse(Total > 0, car5more / Total, 0),
         year = "2021")

dat2022<- 
  get_acs(geography = "tract", 
          variables = c("B08301_001E","B08301_011E",
                        "B08201_001E","B08201_002E",
                        "B08201_003E","B08201_004E",
                        "B08201_005E","B08201_006E",
                        "B08201_007E"), 
          year=2022, state=37, county=119, 
          geometry=TRUE, output="wide") %>%
  st_transform(crs=4326) %>%
  rename(Total = B08201_001E,
         car0 = B08201_002E,
         car1 = B08201_003E,
         car2 = B08201_004E,
         car3 = B08201_005E,
         car4 = B08201_006E,
         car5more = B08201_007E,
         Commutetowork = B08301_001E,
         Workwithbus = B08301_011E) %>%
  mutate(pctworkwithbus = ifelse(Commutetowork > 0, Workwithbus / Commutetowork, 0),
         pctnocar = ifelse(Total > 0, car0 / Total, 0),
         pct1car = ifelse(Total > 0, car1 / Total, 0),
         pct2car = ifelse(Total > 0, car2 / Total, 0),
         pct3car = ifelse(Total > 0, car3 / Total, 0),
         pct4car = ifelse(Total > 0, car4 / Total, 0),
         pct5car = ifelse(Total > 0, car5more / Total, 0),
         year = "2022")
```

## Plots
  
```{r 2017plots, echo=FALSE, fig.height=18, fig.width=12}
tp_vars <- c("pctworkwithbus", "pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
tp_titles <- c("Percent of Population Commute with Bus", "Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
mapList <- list()
j <- 1

for(i in tp_vars){
  map <- ggplot() +
         geom_sf(data = dat2017,aes(fill = (!!sym(i))),crs = st_crs("EPSG:4326")) +
         scale_fill_gradient(low = "#7ACFD3", high = "#005357") + 
         geom_point(data=AllData,aes(x=Longitude, y= Latitude), color = "black", size = 0.5)+
         labs(title = tp_titles[j], caption = paste0("Figure ", as.character(j)))
  mapList[[i]] <- map
  j<-j+1
}

do.call(grid.arrange,c(mapList, ncol=2, top="Commute by Bus and Car Ownership of Mecklenburg County in 2017 (Census Tracts)"))
```

```{r 2018plots, echo=FALSE, fig.height=18, fig.width=12}
tp_vars <- c("pctworkwithbus", "pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
tp_titles <- c("Percent of Population Commute with Bus", "Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
mapList <- list()
j <- 1

for(i in tp_vars){
  map <- ggplot() +
         geom_sf(data = dat2018,aes(fill = (!!sym(i))), crs = st_crs("EPSG:4326")) +
         scale_fill_gradient(low = "#7ACFD3", high = "#005357") + 
         geom_point(data=AllData,aes(x=Longitude, y= Latitude), color = "black", size = 0.5)+
         labs(title = tp_titles[j], caption = paste0("Figure ", as.character(j)))
  mapList[[i]] <- map
  j<-j+1
}

do.call(grid.arrange,c(mapList, ncol=2, top="Commute by Bus and Car Ownership of Mecklenburg County in 2018 (Census Tracts)"))
```

```{r 2019plots, echo=FALSE, fig.height=18, fig.width=12}
tp_vars <- c("pctworkwithbus", "pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
tp_titles <- c("Percent of Population Commute with Bus", "Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
mapList <- list()
j <- 1

for(i in tp_vars){
  map <- ggplot() +
         geom_sf(data = dat2019,aes(fill = (!!sym(i))),crs = st_crs("EPSG:4326")) +
         scale_fill_gradient(low = "#7ACFD3", high = "#005357") + 
         geom_point(data=AllData,aes(x=Longitude, y= Latitude), color = "black", size = 0.5)+
         labs(title = tp_titles[j], caption = paste0("Figure ", as.character(j)))
  mapList[[i]] <- map
  j<-j+1
}

do.call(grid.arrange,c(mapList, ncol=2, top="Commute by Bus and Car Ownership of Mecklenburg County in 2019 (Census Tracts)"))
```

```{r 2020plots, echo=FALSE, fig.height=18, fig.width=12}
tp_vars <- c("pctworkwithbus", "pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
tp_titles <- c("Percent of Population Commute with Bus", "Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
mapList <- list()
j <- 1

for(i in tp_vars){
  map <- ggplot() +
         geom_sf(data = dat2020,aes(fill = (!!sym(i))),crs = st_crs("EPSG:4326")) +
         scale_fill_gradient(low = "#7ACFD3", high = "#005357") + 
         geom_point(data=AllData,aes(x=Longitude, y= Latitude), color = "black", size = 0.5)+
         labs(title = tp_titles[j], caption = paste0("Figure ", as.character(j)))
  mapList[[i]] <- map
  j<-j+1
}

do.call(grid.arrange,c(mapList, ncol=2, top="Commute by Bus and Car Ownership of Mecklenburg County in 2020 (Census Tracts)"))
```

```{r 2021plots, echo=FALSE, fig.height=18, fig.width=12}
tp_vars <- c("pctworkwithbus", "pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
tp_titles <- c("Percent of Population Commute with Bus", "Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
mapList <- list()
j <- 1

for(i in tp_vars){
  map <- ggplot() +
         geom_sf(data = dat2021,aes(fill = (!!sym(i))),crs = st_crs("EPSG:4326")) +
         scale_fill_gradient(low = "#7ACFD3", high = "#005357") + 
         geom_point(data=AllData,aes(x=Longitude, y= Latitude), color = "black", size = 0.5)+
         labs(title = tp_titles[j], caption = paste0("Figure ", as.character(j)))
  mapList[[i]] <- map
  j<-j+1
}

do.call(grid.arrange,c(mapList, ncol=2, top="Commute by Bus and Car Ownership of Mecklenburg County in 2021 (Census Tracts)"))
```

```{r 2022plots, echo=FALSE, fig.height=18, fig.width=12}
tp_vars <- c("pctworkwithbus", "pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
tp_titles <- c("Percent of Population Commute with Bus", "Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
mapList <- list()
j <- 1

for(i in tp_vars){
  map <- ggplot() +
         geom_sf(data = dat2022,aes(fill = (!!sym(i))),crs = st_crs("EPSG:4326")) +
         scale_fill_gradient(low = "#7ACFD3", high = "#005357") + 
         geom_point(data=AllData,aes(x=Longitude, y= Latitude), color = "black", size = 0.5)+
         labs(title = tp_titles[j], caption = paste0("Figure ", as.character(j)))
  mapList[[i]] <- map
  j<-j+1
}

do.call(grid.arrange,c(mapList, ncol=2, top="Commute by Bus and Car Ownership of Mecklenburg County in 2022 (Census Tracts)"))
```

## Histogram

```{r 2017hist, echo=FALSE, fig.height=18, fig.width=12}
car_vars <- c("pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
car_titles <- c("Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
histList <- list()
j <- 1

for(i in car_vars){
  hist <- ggplot(data = dat2017, aes(x = !!sym(i))) +
           geom_histogram(fill = "#005357", color = "black") +
           labs(title = car_titles[j], caption = paste0("Figure ", as.character(j)))
  histList[[i]] <- hist
  j <- j + 1
}

do.call(grid.arrange,c(histList, ncol=2, top="Histogram of Car Ownership of Mecklenburg County in 2017"))

```

```{r 2018hist, echo=FALSE, fig.height=18, fig.width=12}
car_vars <- c("pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
car_titles <- c("Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
histList <- list()
j <- 1

for(i in car_vars){
  hist <- ggplot(data = dat2018, aes(x = !!sym(i))) +
           geom_histogram(fill = "#005357", color = "black") +
           labs(title = car_titles[j], caption = paste0("Figure ", as.character(j)))
  histList[[i]] <- hist
  j<-j+1
}

do.call(grid.arrange,c(histList, ncol=2, top="Histogram of Car Ownership of Mecklenburg County in 2018"))
```

```{r 2019hist, echo=FALSE, fig.height=18, fig.width=12}
car_vars <- c("pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
car_titles <- c("Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
histList <- list()
j <- 1

for(i in car_vars){
  hist <- ggplot(data = dat2019, aes(x = !!sym(i))) +
           geom_histogram(fill = "#005357", color = "black") +
           labs(title = car_titles[j], caption = paste0("Figure ", as.character(j)))
  histList[[i]] <- hist
  j<-j+1
}

do.call(grid.arrange,c(histList, ncol=2, top="Histogram of Car Ownership of Mecklenburg County in 2019"))
```

```{r 2020hist, echo=FALSE, fig.height=18, fig.width=12}
car_vars <- c("pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
car_titles <- c("Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
histList <- list()
j <- 1

for(i in car_vars){
  hist <- ggplot(data = dat2020, aes(x = !!sym(i))) +
           geom_histogram(fill = "#005357", color = "black") +
           labs(title = car_titles[j], caption = paste0("Figure ", as.character(j)))
  histList[[i]] <- hist
  j<-j+1
}

do.call(grid.arrange,c(histList, ncol=2, top="Histogram of Car Ownership of Mecklenburg County in 2020"))
```


```{r 2021hist, echo=FALSE, fig.height=18, fig.width=12}
car_vars <- c("pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
car_titles <- c("Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
histList <- list()
j <- 1

for(i in car_vars){
  hist <- ggplot(data = dat2021, aes(x = !!sym(i))) +
           geom_histogram(fill = "#005357", color = "black") +
           labs(title = car_titles[j], caption = paste0("Figure ", as.character(j)))
  histList[[i]] <- hist
  j<-j+1
}

do.call(grid.arrange,c(histList, ncol=2, top="Histogram of Car Ownership of Mecklenburg County in 2021"))
```


```{r 2022hist, echo=FALSE, fig.height=18, fig.width=12}
car_vars <- c("pctnocar", "pct1car", "pct2car", "pct3car", "pct4car", "pct5car")
car_titles <- c("Percent of Household with No Car", "Percent of Household with 1 Car", "Percent of Household with 2 Cars", "Percent of Household with 3 Cars", "Percent of Household with 4 Cars", "Percent of Household with 5 or more Cars")
histList <- list()
j <- 1

for(i in car_vars){
  hist <- ggplot(data = dat2022, aes(x = !!sym(i))) +
           geom_histogram(fill = "#005357", color = "black") +
           labs(title = car_titles[j], caption = paste0("Figure ", as.character(j)))
  histList[[i]] <- hist
  j<-j+1
}

do.call(grid.arrange,c(histList, ncol=2, top="Histogram of Car Ownership of Mecklenburg County in 2022"))
```

## Car Ownership Trend

```{r trendcar, fig.height=10, fig.width=12}
dat_combined <- bind_rows(
  dat2017,
  dat2018,
  dat2019,
  dat2020,
  dat2021,
  dat2022)

average_pct_cars <- dat_combined %>%
  group_by(year) %>%
  summarise(avg_pct_0cars = mean(pctnocar),
            avg_pct_1cars = mean(pct1car),
            avg_pct_2cars = mean(pct2car),
            avg_pct_3cars = mean(pct3car),
            avg_pct_4cars = mean(pct4car),
            avg_pct_5ormore_cars = mean(pct5car))

average_pct_cars_long <- pivot_longer(average_pct_cars, 
                                      cols = starts_with("avg_pct"), 
                                      names_to = "Cars", 
                                      values_to = "Percentage")

plot_list <- list()
for (i in unique(average_pct_cars_long$Cars)) {
  num_cars <- gsub("avg_pct_", "", i)
  num_cars <- gsub("cars", "car", num_cars)
  subset_data <- subset(average_pct_cars_long, Cars == i)
  plot <- ggplot(subset_data, aes(x = year, y = Percentage, group = 1)) +
    geom_line(color = "black",linewidth=1.5) +
    geom_point(color = "red",size=3) +
    labs(x = "Year", 
         y = "Average Percentage of Households",
         title = paste("Trend of Car Ownership:", num_cars)) +
    scale_y_continuous(labels = scales::percent_format(accuracy = 0.1)) +
    theme_minimal()
  plot_list[[i]] <- plot
}

grid.arrange(grobs = plot_list, ncol = 2, top = "Trend of Car Ownership (2017-2022)")
```

## Commute by Bus Trend

```{r}
dat_combined$year <- as.numeric(dat_combined$year)
average_pct_bus <- dat_combined %>%
  group_by(year) %>%
  summarise(avg_pct_bus = mean(pctworkwithbus))

ggplot(average_pct_bus, aes(x = year, y = avg_pct_bus)) +
  geom_line(color = "black",linewidth=1.5) +
  geom_point(color = "red",size=3) +
  labs(x = "Year", 
       y = "Average Percentage of Population Commuting with Bus",
       title = "Trend of Commuting by Bus from 2017 to 2022") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 0.1)) +
  theme_minimal()
```

